name: Run JAR File

# Run the workflow on specific events, e.g., push, schedule, or manually
on:
  push:
    branches:
      - feature_authentication_service  # or the branch name you want
  schedule:
    - cron: '27 16 * * *'  # Run at 4:27 PM UTC, which is 9:57 PM Sri Lanka Time
  workflow_dispatch:  # Allow manual triggering

jobs:
  run_jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Run JAR file
        run: java -jar authenticationservice/authenticationservice/out/artifacts/authenticationservice_jar/authenticationservice.jar
